name: Build and Deploy Code

on: [push, pull_requests]

jobs:
    job1:
        runs_on: ubuntu-latest
        steps:
            - name: pulling git repo
              uses: actions/checkout@v2
            - name: validate that command works
              run: echo "hello world"
              